// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rank_asR
IntegerVector rank_asR(NumericVector x, bool decreasing);
RcppExport SEXP _changepointGA_rank_asR(SEXP xSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_asR(x, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// selectTau_cpp
arma::vec selectTau_cpp(int n, int minDist, double Pb, int mmax, int lmax);
RcppExport SEXP _changepointGA_selectTau_cpp(SEXP nSEXP, SEXP minDistSEXP, SEXP PbSEXP, SEXP mmaxSEXP, SEXP lmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type minDist(minDistSEXP);
    Rcpp::traits::input_parameter< double >::type Pb(PbSEXP);
    Rcpp::traits::input_parameter< int >::type mmax(mmaxSEXP);
    Rcpp::traits::input_parameter< int >::type lmax(lmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(selectTau_cpp(n, minDist, Pb, mmax, lmax));
    return rcpp_result_gen;
END_RCPP
}
// random_population_cpp
arma::mat random_population_cpp(int popsize, int n, int minDist, double Pb, int mmax, int lmax);
RcppExport SEXP _changepointGA_random_population_cpp(SEXP popsizeSEXP, SEXP nSEXP, SEXP minDistSEXP, SEXP PbSEXP, SEXP mmaxSEXP, SEXP lmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type popsize(popsizeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type minDist(minDistSEXP);
    Rcpp::traits::input_parameter< double >::type Pb(PbSEXP);
    Rcpp::traits::input_parameter< int >::type mmax(mmaxSEXP);
    Rcpp::traits::input_parameter< int >::type lmax(lmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(random_population_cpp(popsize, n, minDist, Pb, mmax, lmax));
    return rcpp_result_gen;
END_RCPP
}
// offspring_uniformcrossover_cpp
arma::vec offspring_uniformcrossover_cpp(arma::vec& mom, arma::vec& dad, int minDist, int lmax, int n);
RcppExport SEXP _changepointGA_offspring_uniformcrossover_cpp(SEXP momSEXP, SEXP dadSEXP, SEXP minDistSEXP, SEXP lmaxSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type mom(momSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type dad(dadSEXP);
    Rcpp::traits::input_parameter< int >::type minDist(minDistSEXP);
    Rcpp::traits::input_parameter< int >::type lmax(lmaxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(offspring_uniformcrossover_cpp(mom, dad, minDist, lmax, n));
    return rcpp_result_gen;
END_RCPP
}
// selection_linearrank_cpp
List selection_linearrank_cpp(arma::mat& pop, arma::vec& popFit);
RcppExport SEXP _changepointGA_selection_linearrank_cpp(SEXP popSEXP, SEXP popFitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type popFit(popFitSEXP);
    rcpp_result_gen = Rcpp::wrap(selection_linearrank_cpp(pop, popFit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_changepointGA_rank_asR", (DL_FUNC) &_changepointGA_rank_asR, 2},
    {"_changepointGA_selectTau_cpp", (DL_FUNC) &_changepointGA_selectTau_cpp, 5},
    {"_changepointGA_random_population_cpp", (DL_FUNC) &_changepointGA_random_population_cpp, 6},
    {"_changepointGA_offspring_uniformcrossover_cpp", (DL_FUNC) &_changepointGA_offspring_uniformcrossover_cpp, 5},
    {"_changepointGA_selection_linearrank_cpp", (DL_FUNC) &_changepointGA_selection_linearrank_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_changepointGA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
